config/routes.rb
Workspace::Application.routes.draw do

  resources :dogs

  get "welcome" => 'static_pages#welcome'
  get "about" => 'static_pages#about'

  get 'sign_up' => 'users#new'
  get "user_by_name/:name" => 'users#show_by_name'
    devise_for :users
  resources :users
  resources :cats
  get 'orange_cats' => 'cats#orange_cats'
  root 'static_pages#welcome'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :name, presence: true
    validates :email,   presence: true, 
                        format: { with: /\A\S+@\w+\.\w+\z/, 
                            message: 'format is invalid' }
                            

    #has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instea
  
  before_filter :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    
    def index
        @cats = Cat.all
    end
    
    def show
        @cat = Cat.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        redirect_to cats_path, notice: 'No cats found'
    end
    
    def new
        @cat = Cat.new
    end
    
    def edit
        @cat = Cat.find(params[:id])
    end
    
    def update
       @cat = Cat.find(params[:id]) 
       
       if @cat.update_attributes(valid_cat_params)
          redirect_to cat_url(id: @cat.id), notice: 'Successfully Updated Kitty!' 
       else
           flash[:notice] = "Couldn't update Kitteh :("
           render :edit
           
       end
    end
    
    def create
        @cat = Cat.new(valid_cat_params)
        
        if @cat.save
            redirect_to cats_show_path(id: @cat.id), notice: 'Successfully Created a Cat'
        else
            flash[:notice] = "Failed to Create Cat"
            render :new
        end
    end
    
    def destroy
        @cat = Cat.find(params[:id])
        if @cat.delete
           redirect_to cats_path, notice: 'Deleted Kitteh :`('
        else
            redirect_to request.referrer, "Couldn't destroy kitty"
        end
    end
    
    
    def orange_cats
    end
    
    def valid_cat_params
       params.require(:cat).permit(:name, :colour) 
    end
        
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dog }
      else
        format.html { render action: 'new' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :colour)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        @user = User.where(email: params[:session][:email]).first
        
        if @user
            if @user.authenticate(params[:session][:password]) 
               session[:user_id] = @user.id
               redirect_to root_path, notice: 'Successfully Signed In'
            else
                flash[:notice] = "Incorrect Username/Password"
                render :new
            end
        else
            flash[:notice] = "User could not be found"
            render :new
        end
    end
    
    def destroy
        if session[:user_id]
           session[:user_id] = nil 
           redirect_to root_path, notice: 'Successfully signed Out. Come again!'
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end

  def about
    @cat = Cat.first
    render 'cats/show'
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      # Send the welcome email
      UserMailer.welcome_email(@user).deliver
      redirect_to user_path(id: @user.id), notice: 'Thanks for Signing Up!'
    else

      render :new
    end
  end
  
  
  def show_by_name
    
    @user = User.where(name: params[:name]).first
    
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def current_user
       if !session[:user_id].blank?
          current_user = User.find(session[:user_id]) 
       else
        current_user = nil
       end
       
       return current_user
    end
    
    
    def current_user_logged_in?
       if current_user
           true
       else
           false
       end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_form.html.erb
<%= form_for @cat do |f| %> 
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
     <div class="form-group">
        <%= f.label :colour %>
        <%= f.select :colour, [['Red', 'red'], ['Orange','orange'], ['Black', 'black']] %>
    </div>
    <div class="form-group">
        <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Edit <%= @cat.name %>'s Details</h1>

<%= render 'form' %>

app/views/cats/index.html.erb
<h1> All Cats</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Destroy Kitty?</th>
    </tr>
     <% @cats.each do |c| %>
    
    <tr>
        <td> <%= link_to c.name, edit_cat_path(id: c.id) %> who is <%= c.colour %> in colour. </td>
        <td><%= link_to "Destroy Kitty", cat_path(id: c.id), method: :delete, confirm: 'Are you sure?' %> </td>
    </tr>
           
      
    <% end %>   
    
</table>
    

app/views/cats/new.html.erb
<h1>Create a Cat</h1>

<%= render 'form' %>

app/views/cats/show.html.erb
<% if @cat.nil? %>
    No Cat found. Sorry!
<% else %>
    <h1><%= @cat.name %></h1>
    This cat is <%= @cat.colour %> in colour.
<% end %>

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Colour</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.colour %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @dog.colour %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class='col-xs-4'>
        <h1>Whatimeisit</h1>
    </div>
    <div class='col-xs-4 col-xs-offset-4'>
        <ul class="nav nav-pills" role="tablist">

          <li role="presentation" <%= current_page?('/' ) ? "class=active" : "" %> ><%= link_to 'Home', root_path %></li>
          <li role="presentation" <%= current_page?(controller: '/cats', action: 'index') ? "class=active" : "" %>  ><%= link_to 'ListCats', cats_path %></li>
          <li role="presentation" <%= current_page?(controller: '/static_pages', action: 'about') ? "class=active" : "" %> ><%= link_to 'About', about_path %></li>
          <% 
              if user_signed_in?
                  the_link = link_to 'Sign Out', destroy_user_session_path, method: :delete
              else
                  the_link = link_to 'Sign In', new_user_session_path 
              end
          %>
          <li role="presentation"> <%=  the_link %></li>
        </ul>
        
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<div class="container">
  <%= yield %>
</div>




</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Whatimeisit</h1>
<p>Whatimeisit is an app to tell the time in one country when you know the time in another.</p>

app/views/static_pages/welcome.html.erb
<div class="jumbotron">
<%= @user.inspect %>
  <h1>Welcome to Whatimeisit!</h1>
  <p>You can now find out what time it will be next Friday at 3 am your time in Canada!</p>

  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %> 
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
     <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email%>
    </div>
     <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password%>
    </div>
     <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="form-group">
        <!-- If new user, let's call the button "Sign Up", if existing, then "Update" -->
       
        <% if @user.new_record? %>
            <% submit_label = "Sign Up" %>
        <% else %>
             <% submit_label = "Update" %>
        <% end %>
        
            <%= f.submit submit_label, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>List of all Users</h1>

<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
        </tr>
    <% end %>
</table>

app/views/users/new.html.erb
<h1>Register an Account Now!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<table>
    <tr>
        <td>
            Name:
        </td>
        <td>
            <%= @user.name %>
        </td>
    </tr>
    <tr>
        <td>
            Email:
        </td>
        <td>
            <%= @user.email %>
        </td>
    </tr>
</table>

app/views/users/show_by_name.html.erb
<h1> <%= @user.name %></h1>

<table>
    
    <tr>
        
        <td>Name</td>
        
        <td> <%= @user.name %></td>
        
    </tr>
    
    
    <tr>
        
        <td>Email</td>
        
        <td> <%= @user.email %></td>
        
        
        
    </tr>
    
</table>